In [3]:
# Import the dependencies and libraries 
import pandas as pd
import gmaps
import numpy as np
import requests

from citipy import citipy
# Import the API key.
from config import g_key

from datetime import datetime
import time

In [4]:
# Store the CSV you saved created in part one into a DataFrame.
cityWeatherdatadf = pd.read_csv("Data/WeatherPy_challenge.csv")
cityWeatherdatadf.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches(last 3hrs),Snow inches(last 3hrs)
0,0,Punta Arenas,CL,2020-01-06 03:06:30,-53.16,-70.91,46.4,61,40,12.75,scattered clouds,0.00,0.0
1,1,Hobart,AU,2020-01-06 03:04:03,-42.88,147.33,77.0,55,20,17.22,few clouds,0.00,0.0
2,2,Brae,GB,2020-01-06 03:06:30,60.40,-1.35,50.0,87,100,17.22,light rain,0.44,0.0
3,3,Kapaa,US,2020-01-06 03:02:49,22.08,-159.32,80.6,74,75,19.46,broken clouds,0.00,0.0
4,4,Nantucket,US,2020-01-06 03:06:30,41.28,-70.10,35.6,55,1,11.41,clear sky,0.00,0.0

In [5]:
# Create a column with Yes or No for rain
cityWeatherdatadf['Want Rain?(y/n)'] = np.where(cityWeatherdatadf['Rain inches(last 3hrs)']>0, 'yes', 'no')
cityWeatherdatadf

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches(last 3hrs),Snow inches(last 3hrs),Want Rain?(y/n)
0,0,Punta Arenas,CL,2020-01-06 03:06:30,-53.16,-70.91,46.40,61,40,12.75,scattered clouds,0.00,0.0,no
1,1,Hobart,AU,2020-01-06 03:04:03,-42.88,147.33,77.00,55,20,17.22,few clouds,0.00,0.0,no
2,2,Brae,GB,2020-01-06 03:06:30,60.40,-1.35,50.00,87,100,17.22,light rain,0.44,0.0,yes
3,3,Kapaa,US,2020-01-06 03:02:49,22.08,-159.32,80.60,74,75,19.46,broken clouds,0.00,0.0,no
4,4,Nantucket,US,2020-01-06 03:06:30,41.28,-70.10,35.60,55,1,11.41,clear sky,0.00,0.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,545,Alegrete,BR,2020-01-06 03:07:19,-29.79,-55.79,76.62,55,20,11.74,few clouds,0.00,0.0,no
546,546,Batagay,RU,2020-01-06 03:07:19,67.65,134.64,-20.81,87,50,1.43,scattered clouds,0.00,0.0,no
547,547,Coahuayana,MX,2020-01-06 03:07:19,18.62,-100.35,72.73,48,0,3.58,clear sky,0.00,0.0,no
548,548,Dongsheng,CN,2020-01-06 03:07:19,29.72,112.52,45.14,90,100,8.21,light rain,0.19,0.0,yes
549,549,Dapitan,PH,2020-01-06 03:07:19,10.27,123.95,84.20,70,20,8.05,few clouds,0.00,0.0,no

In [6]:
# Create a column with Yes or No for snow
cityWeatherdatadf['Want Snow?(y/n)'] = np.where(cityWeatherdatadf['Snow inches(last 3hrs)']>0, 'yes', 'no')
cityWeatherdatadf

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches(last 3hrs),Snow inches(last 3hrs),Want Rain?(y/n),Want Snow?(y/n)
0,0,Punta Arenas,CL,2020-01-06 03:06:30,-53.16,-70.91,46.40,61,40,12.75,scattered clouds,0.00,0.0,no,no
1,1,Hobart,AU,2020-01-06 03:04:03,-42.88,147.33,77.00,55,20,17.22,few clouds,0.00,0.0,no,no
2,2,Brae,GB,2020-01-06 03:06:30,60.40,-1.35,50.00,87,100,17.22,light rain,0.44,0.0,yes,no
3,3,Kapaa,US,2020-01-06 03:02:49,22.08,-159.32,80.60,74,75,19.46,broken clouds,0.00,0.0,no,no
4,4,Nantucket,US,2020-01-06 03:06:30,41.28,-70.10,35.60,55,1,11.41,clear sky,0.00,0.0,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,545,Alegrete,BR,2020-01-06 03:07:19,-29.79,-55.79,76.62,55,20,11.74,few clouds,0.00,0.0,no,no
546,546,Batagay,RU,2020-01-06 03:07:19,67.65,134.64,-20.81,87,50,1.43,scattered clouds,0.00,0.0,no,no
547,547,Coahuayana,MX,2020-01-06 03:07:19,18.62,-100.35,72.73,48,0,3.58,clear sky,0.00,0.0,no,no
548,548,Dongsheng,CN,2020-01-06 03:07:19,29.72,112.52,45.14,90,100,8.21,light rain,0.19,0.0,yes,no
549,549,Dapitan,PH,2020-01-06 03:07:19,10.27,123.95,84.20,70,20,8.05,few clouds,0.00,0.0,no,no

In [7]:
#Get the data types
cityWeatherdatadf.dtypes

City_ID                     int64
City                       object
Country                    object
Date                       object
Lat                       float64
Lng                       float64
Max Temp                  float64
Humidity                    int64
Cloudiness                  int64
Wind Speed                float64
Current Description        object
Rain inches(last 3hrs)    float64
Snow inches(last 3hrs)    float64
Want Rain?(y/n)            object
Want Snow?(y/n)            object
dtype: object

In [8]:
cityWeatherdatadf.count()

City_ID                   550
City                      550
Country                   547
Date                      550
Lat                       550
Lng                       550
Max Temp                  550
Humidity                  550
Cloudiness                550
Wind Speed                550
Current Description       550
Rain inches(last 3hrs)    550
Snow inches(last 3hrs)    550
Want Rain?(y/n)           550
Want Snow?(y/n)           550
dtype: int64

In [9]:
# Ask the customer to add a minimum and maximum temperatures. Ask they if they want it to rain and snow with option to respond to the textbox.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
rain_want = str(input("Do you want it to be raining? (yes/no)"))
snow_want = str(input("Do you want it to be snowing? (yes/no)"))

What is the minimum temperature you would like for your trip? 10
What is the maximum temperature you would like for your trip? 95
Do you want it to be raining? (yes/no)yes
Do you want it to be snowing? (yes/no)no

In [10]:
# Filter the dataset to find the cities that fit the criteria.
filteredCities_df = cityWeatherdatadf.loc[(cityWeatherdatadf["Max Temp"] <= max_temp) & \
                                          (cityWeatherdatadf["Max Temp"] >= min_temp) & \
                                          (cityWeatherdatadf["Want Rain?(y/n)"] == rain_want) & \
                                          (cityWeatherdatadf["Want Snow?(y/n)"] == snow_want)]

In [11]:
#create a dataframe of the filtered data 
filteredCities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches(last 3hrs),Snow inches(last 3hrs),Want Rain?(y/n),Want Snow?(y/n)
2,2,Brae,GB,2020-01-06 03:06:30,60.40,-1.35,50.00,87,100,17.22,light rain,0.44,0.0,yes,no
25,25,Mataura,NZ,2020-01-06 03:06:32,-46.19,168.86,50.00,83,100,21.00,light rain,1.19,0.0,yes,no
32,32,Kiama,AU,2020-01-06 03:06:32,-34.67,150.86,73.00,73,100,12.75,light rain,0.19,0.0,yes,no
34,34,Sao Mateus Do Maranhao,BR,2020-01-06 03:06:33,-4.04,-44.48,74.08,96,98,2.73,light rain,0.19,0.0,yes,no
41,41,Atuona,PF,2020-01-06 03:06:33,-9.80,-139.03,79.90,78,63,10.71,light rain,1.75,0.0,yes,no
48,48,Karratha,AU,2020-01-06 03:03:28,-20.74,116.85,87.49,64,100,6.98,light rain,0.25,0.0,yes,no
59,59,Cayenne,GF,2020-01-06 03:03:06,4.94,-52.33,77.00,88,42,3.36,light rain,0.19,0.0,yes,no
67,67,Dingle,PH,2020-01-06 03:06:35,11.00,122.67,79.36,85,97,16.37,light rain,1.44,0.0,yes,no
72,72,Arraial Do Cabo,BR,2020-01-06 03:02:44,-22.97,-42.02,76.08,86,100,2.51,light rain,0.63,0.0,yes,no
81,81,Dzilam Gonzalez,MX,2020-01-06 03:06:37,21.28,-88.93,72.73,74,1,17.69,light rain,0.13,0.0,yes,no

In [12]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [13]:
# New data frame to include the filtered list and add the hotel name.
filteredcityhotels_df = filteredCities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()
filteredcityhotels_df["Hotel Name"] = ""

In [14]:
filteredcityhotels_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Brae,GB,50.00,light rain,60.40,-1.35,
25,Mataura,NZ,50.00,light rain,-46.19,168.86,
32,Kiama,AU,73.00,light rain,-34.67,150.86,
34,Sao Mateus Do Maranhao,BR,74.08,light rain,-4.04,-44.48,
41,Atuona,PF,79.90,light rain,-9.80,-139.03,
48,Karratha,AU,87.49,light rain,-20.74,116.85,
59,Cayenne,GF,77.00,light rain,4.94,-52.33,
67,Dingle,PH,79.36,light rain,11.00,122.67,
72,Arraial Do Cabo,BR,76.08,light rain,-22.97,-42.02,
81,Dzilam Gonzalez,MX,72.73,light rain,21.28,-88.93,
82,Ponta Do Sol,BR,66.60,light rain,-20.63,-46.00,
107,Gravdal,NO,48.00,moderate rain,59.79,5.78,
113,Kaitangata,NZ,53.01,light rain,-46.28,169.85,
123,Faanui,PF,82.38,light rain,-16.48,-151.75,
140,Antalaha,MG,80.06,light rain,-14.90,50.28,
157,Nalut,LY,49.51,light rain,31.86,10.98,
164,Butaritari,KI,85.01,moderate rain,3.07,172.79,
165,Kendari,ID,78.87,moderate rain,-3.99,122.52,
168,Port-Gentil,GA,82.04,light rain,-0.72,8.78,
186,Gobabis,NaN,69.62,light rain,-22.45,18.97,
199,Nova Vicosa,BR,74.41,light rain,-17.89,-39.37,
215,Linhares,BR,72.95,light rain,-19.38,-40.06,
218,Kudahuvadhoo,MV,82.49,light rain,2.67,72.89,
243,Tuatapere,NZ,50.00,light rain,-46.13,167.69,
250,Manokwari,ID,79.05,light rain,-0.87,134.08,
251,Isangel,VU,78.17,light rain,-19.55,169.27,
283,Tuy Hoa,VN,74.68,light rain,13.08,109.30,
290,Vanimo,PG,82.02,light rain,-2.67,141.30,
303,Barcelos,BR,75.79,light rain,-0.97,-62.93,
322,Maoming,CN,73.45,light rain,21.67,110.92,
332,Ntcheu,MW,60.58,light rain,-14.82,34.64,
354,Te Anau,NZ,43.54,light rain,-45.41,167.72,
359,Chaman,AF,44.94,moderate rain,30.92,66.46,
362,Banjar,ID,87.51,light rain,-7.37,108.54,
386,Salinopolis,BR,82.08,light rain,-0.61,-47.36,
418,Caravelas,BR,71.42,light rain,-17.73,-39.27,
428,Duyun,CN,58.35,light rain,26.27,107.52,
442,San Policarpo,PH,82.27,light rain,12.18,125.51,
447,San Luis,AR,66.06,light rain,-33.30,-66.34,
449,Wewak,PG,80.94,light rain,-3.55,143.63,
459,Mabiton,PH,78.76,light rain,12.83,123.26,
461,Kirakira,SB,83.91,light rain,-10.46,161.92,
465,Port Keats,AU,90.77,light rain,-14.25,129.55,
500,Garh Maharaja,PK,50.07,light rain,30.83,71.90,
504,Nushki,PK,48.65,moderate rain,29.55,66.02,
505,Ulladulla,AU,71.60,light rain,-35.36,150.48,
511,Katherine,AU,93.20,light rain,-14.47,132.26,
514,Nortelandia,BR,73.02,light rain,-14.45,-56.80,
515,Barkhan,PK,42.28,light rain,29.90,69.52,
518,Sola,TZ,63.32,light rain,-3.17,33.80,
526,Flinders,AU,73.99,light rain,-34.58,150.85,
528,Manaure,CO,79.59,light rain,11.78,-72.45,
529,Pekalongan,ID,83.70,light rain,-6.89,109.67,
536,Traralgon,AU,59.00,light rain,-38.19,146.54,
548,Dongsheng,CN,45.14,light rain,29.72,112.52,

In [15]:
filteredcityhotels_df.count()

City                   55
Country                54
Max Temp               55
Current Description    55
Lat                    55
Lng                    55
Hotel Name             55
dtype: int64

In [16]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}

In [17]:
 # Iterate through the DataFrame.
for index, row in filteredcityhotels_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to the params dictionary as values to the location key.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        filteredcityhotels_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.

In [18]:
# Add a heatmap of temperature for the vacation spots.
locations = filteredcityhotels_df[["Lat", "Lng"]]
max_temp = filteredcityhotels_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
filteredcityhotels_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Brae,GB,50.00,light rain,60.40,-1.35,Busta House Hotel
25,Mataura,NZ,50.00,light rain,-46.19,168.86,Ellie's Villa
32,Kiama,AU,73.00,light rain,-34.67,150.86,The Sebel Kiama Harbourside
34,Sao Mateus Do Maranhao,BR,74.08,light rain,-4.04,-44.48,Pousada Pingo De Ouro
41,Atuona,PF,79.90,light rain,-9.80,-139.03,Villa Enata
48,Karratha,AU,87.49,light rain,-20.74,116.85,ibis Styles Karratha
59,Cayenne,GF,77.00,light rain,4.94,-52.33,Hôtel Le Dronmi
67,Dingle,PH,79.36,light rain,11.00,122.67,Camp Pasica
72,Arraial Do Cabo,BR,76.08,light rain,-22.97,-42.02,Pousada Porto Praia
81,Dzilam Gonzalez,MX,72.73,light rain,21.28,-88.93,Amina

In [20]:
# Create the output file (CSV).
output_data_file = "Data/WeatherPy_vacation.csv"
# Export the City_Data into a CSV.
filteredcityhotels_df.to_csv(output_data_file, index_label="City_ID")

In [21]:
# Add a heatmap of temperature for the vacation spots.
locations = filteredcityhotels_df[["Lat", "Lng"]]
max_temp = filteredcityhotels_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [22]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description} °F</dd>
</dl>
"""

In [23]:
# Store the DataFrame Row for filtered hotels
hotel_map = [info_box_template.format(**row) for index, row in filteredcityhotels_df.iterrows()]

In [24]:
# Map and ddd pop-up marker for each city.
locations = filteredcityhotels_df[["Lat", "Lng"]]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_map)

fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))